version: "2"

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
